name: 
  - UNET_Road_Env
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - tensorflow
  - scipy
  - data
  - seaborne
  - conda
