name: road_id

dependencies:
  - python
  - pip
  - numpy
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - tensorflow
  - keras
  - scikit-learn
  - pip:
    - git+https://github.com/blaze/dask.git#egg=dask[complete]
